---
title: "Modeling in Ecological Research"
author: "Ana C.R. Gomez"
date: "Winter 2020"
output: rmdformats::readthedown
---
#Welcome!

Welcome to my TA page for EEB C119B/C219B.

My office hours are in TLSB 4000, tentatively Mondays 2:00 to 3:00pm. You can also schedule an appointment by email (acrgomez at ucla dot edu).

Please bring a computer to every discussion. As a reminder, it is possible to borrow one from UCLA library.

Students may choose to attend either discussion A (foundational R skills and modeling topics) or discussion B (other topics in R and modeling), or both.

Discussion A will be held Wednesdays 1pm at Terasaki 4000.

Discussion B will be held Thursdays 1pm at Terasaki 4000.




# Week 1

### Everyone:

Please fill out this google forms survey https://forms.gle/D1hY7V8zQzBvHpgs9

### If you are a complete R novice

[Install R](http://cran.us.r-project.org/)

[Install R Studio](https://www.rstudio.com/). R Studio is a free IDE (integrated development environment) for the R language that keeps things organized on your screen. You can use R without R Studio, but I do not recommend it.

### If you are new to R

Before our next discussion, read through Chapter 1 of [A ModernDive into R and the tidyverse](https://moderndive.netlify.com/1-getting-started.html), which explains the basics of how to use RStudio, how to run simple code, and what are R packages.


### If you are new-ish to R

Here is a non-comprehensive list of coding skills that are likely to be important for this class:

* Basic operations and built-in functions
* Basic data manipulation (data frames)
* Writing functions
* Using an ODE solver
* Using random number generators
* Basic matrix algebra (for matrix models)
* Plotting (scatterplots, barplots, boxplots)
* Debugging
* Googling the error message and asking for help

In order to make this class work for everyone, I will cover these topics in discussion. There is always more to know, but if you are confident about your knowledge of them, you can skip some discussion sections (more on this after we get the survey results!).


### If you are an advanced R user

If you are an experienced R user, I would like to share this resource from the RStudio team: [What They Forgot to Teach You About R](https://rstats.wtf/)

We will be discussing advanced skills in some discussions in this class. If you have a particular interest, something you have always wanted to understand better, let me know and I will try to incorporate it!

### If you have coded in languages other than R before

If you have more-than-basic experience coding in languages other than R know that I will not force you to use R, but I may not be able to help you develop your code in other languages. I still recommend taking this opportunity to learn R, since it has some unique features that can be very useful.

RStudio now has full Python support, which makes it easier to use R and Python together. Read more about it here: https://support.rstudio.com/hc/en-us/articles/360023654474-Installing-and-Configuring-Python-with-RStudio

For an experienced coder prespective into learning R, I recommend reading [RInferno](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf)

*Note: while other coding languages are fine, point-and-click analysis software is not going to work for this class*

## Week 1 discussion pdf

Is [here](disc1.pdf)

## Week 1 lecture pdfs
 
[Lecture 1: Introduction](lecture1.pdf)

[Lecture 2: Model formulations](lecture2.pdf)


# Week 2

Discussion A (Wednesdays 1pm) will be on simulating an ODE model. The worksheet is [here](disc2.pdf)

Discussion B (Thursdays 1 pm) will be on data frames using dplyr. The worksheet is [here](discdplyr.pdf)


### Week 3 Instructions

[Here](week3instructions.pdf) are the instructions for presentations and the proposal for week 3.


# Week 3

Student presentations on Week 3 will be at Terasaki 4000.

## Week 3 Discussion 

Discussion A worksheet is [here](disc3.pdf)

Discussion B worksheet is [here](discggplot.pdf)


# Week 5 

Discussion A worksheet is [here](disc5.pdf)

Discussion B worksheet is [here](gillespie.pdf)


# Week 6

For discussion A we will be talking about lubridate. A lubridate cheat sheet is available [here](https://rawgit.com/rstudio/cheatsheets/master/lubridate.pdf)
